spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/InsuranceService_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1

jwt:
  singerKey: "PC8kxKGhdSmTjsgrnxy6r4qamn8fmrtkexw9EQCa02A="
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second
