spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1

jwt:
  singerKey: "PC8kxKGhdSmTjsgrnxy6r4qamn8fmrtkexw9EQCa02A="
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second

cloudinary:
  cloud-name: dcpj8cfng
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}


payment:
  vnPay:
    tmnCode: ${PAYMENT_TMNCODE}
    secretKey: ${PAYMENT_SECRETKEY}
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:8080/api/v1/payment/vnpay-return
    timeout: 15 #in minute
    version: 2.1.0
    command: pay
    orderType: other